### ISSUE TITLE
video jerks on opi0 (h3, armhf, 32 bit)

### ISSUE THREAD

**Issue by sgerwk** [pesintta/vdr-plugin-vaapidevice#26]
Hi,

softhddevice does not play video smoothly on the Orange Pi Zero (is a 32-bit armhf SoC with vdpau).
Here is an example output:
http://sgerwk.altervista.org/output.mpg

The transport stream coming from the dvb stick looks like this:
http://sgerwk.altervista.org/input.ts
(same channels, a few seconds later).

mpv has no problem playing dvb:// with vdpau.

Maybe the problem is with the timing of playing of the frames. A quick hack is to increase the delay from 1 * 1000 to 18 * 1000 in video.c:

    if (!decoded) {                     // nothing decoded, sleep
        // FIXME: sleep on wakeup
        usleep(18 * 1000);
    }

This only avoid frames being shown too quickly, is not a real solution. Maybe the problem is with the SoC being 32 bits.

**Comment by unf** [comment]
In case you haven't seen it, this is just a fork of vdr-plugin-softhddevice to add support Intel GPU using vpp/va-api. Nothing has been changed on VDPAU part, but the vpp/va-api hasn't unfortunately been merged to original upstream.

You may ask the original author regarding VDPAU and open issues here:

- https://projects.vdr-developer.org/projects/plg-softhddevice
- https://projects.vdr-developer.org/git/vdr-plugin-softhddevice.git

**Comment by sgerwk** [comment]
Among the many forks and branches of softhddevice this is the only one that works for me. With the original versions, and also the other branches of this one, what I get is this:
http://sgerwk.altervista.org/output2.mpg

So, something must have been changed from the original version, at least in the part that is common between vdpau and vaapi.

**Comment by unf** [comment]
Well, sure va-api part has been changed to add vpp. But as long as you don't provide a proper fix as pull request, I don't see anybody fixing things for your OrangePi.

VDPAU seems to be a dead horse. Nvidia did not develop/improve it since a long time and will not do any further development obviuously. Existing hardware will surely work for quite a while, as Nvidia's binary drivers still carries that API and it's also implemented into open source nouveau driver, but missing VDPAUs best things of video post processing.

Alternatively you might checkout that VDR nativ video output for Raspberry Devices:

- https://projects.vdr-developer.org/git/vdr-plugin-rpihddevice.git

**Comment by unf** [comment]
And please check that thread @ vdr-portal:

- https://www.vdr-portal.de/forum/index.php?thread/127183-orange-pi-g%C3%BCnstiges-vdr-board/&postID=1251770#post1251770

look at the last posts, they are in english.

**Comment by pesintta** [comment]
Closing this issue as we're dropping VDPAU support in favor of VA-API from this fork of softhddevice.

To further emphaisize that we're renaming this plugin to vaapidevice.
I suspect rpihddevice is the way to go for output on various Pi devices.
